name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.repository }}/powershell-break.md
      - name: PowerShell script
        uses: Amadevus/pwsh-script@v1.0.0
        with:
          script: |
            #Write-ActionDebug "This will be visible only when ACTIONS_STEP_DEBUG secret is set"
            #$result = Invoke-WebRequest "https://test3164645.azurewebsites.net/api/HttpTrigger1?name=testparworkflow"
            
            #Write-ActionDebug $result.Content
            
            $test = get-content "$($github.repository)/powershell-break.md"
            echo "hello"
            echo "$test"

            # we have access to full context objects:
            if ($github.event.repository.full_name -ne $github.repository) {
              throw "something fishy's going on, repos don't match" # will cause step to fail
            }
            
            Write-ActionDebug "$($github)"
            Write-ActionDebug $github.event.repository.full_name
