name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        shell: powershell
        run: |
          $MarkdownFile= Get-Content ./powershell-break.md
          $MarkdownFile | Select-String '(?smi)^metadata.*?.+?' | %{($_ -split ":")[0]}
          $mdcontent = $MarkdownFile| Select-String '(?smi)^metadata.*?.+?' -notmatch | select-string '(?smi)^---' -notmatch
          Write-Output "The mdcontent is $mdcontent"
          $result = Invoke-WebRequest "https://test3164645.azurewebsites.net/api/HttpTrigger1?name=testparworkflow"
          Write-Output $result
