name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        shell: powershell
        env:
           AzureTableUri: ${{ secrets.AZURE_TABLE_URI }}
        run: |
          $MarkdownFile= Get-Content ./powershell-break.md
          $hashtable =@{}
          $MarkdownFile | Select-String '(?smi)^metadata.*?.+?' | %{$hashtable.Add(($_ -split ":")[0],(($_ -split ":")[1]).substring(1))}
          $mdcontent = $MarkdownFile| Select-String '(?smi)^metadata.*?.+?' -notmatch | select-string '(?smi)^---' -notmatch
          $hashtable.Add("mdcontent",$mdcontent)
          $body = $hashtable | convertto-Json
          
          $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
          $headers.Add("Content-Type", "application/json")
          $headers.Add("Accept", "application/json;odata=fullmetadata")
          
          $response = Invoke-WebRequest "$env:AzureTableUri" -Headers $headers -Body $Body -Method 'POST'
          $response.rawcontent
